swagger: '2.0'
info:
  title: ORDS generated API for web
  version: 1.0.0
host: dev.jag.gov.bc.ca
basePath: /ords/deva/vipsords/web
schemes:
- http
produces:
- application/json
securityDefinitions:
  basicAuth:
    type: basic
    description: HTTP Basic Authentication.
tags:
- name: Document
- name: Health
paths:
  /health:
    get:
      tags:
      - Health
      security:
      - basicAuth: []
      operationId: health
      description: Dummy endpoint to check that API calls are working
      responses:
        '200':
          description: output of the endpoint
          schema:
            $ref: '#/definitions/healthOrdsResponse'
  /vipsDocument:
    post:
      tags:
      - Document
      security:
      - basicAuth: []
      description: Store a VIPS document
      responses:
        '200':
          description: output of the endpoint
          schema:
            $ref: '#/definitions/vipsDocumentOrdsResponse'
        '400':
          description: output of the endpoint
          schema:
            $ref: '#/definitions/errorMessage'
      consumes:
      - application/json
      parameters:
      - name: type_code
        in: query
        type: string
        required: true
        description: Implicit parameter
      - name: metadata
        in: query
        type: string
        required: true
        description: Implicit parameter
      - name: mime_type
        in: query
        type: string
        required: true
        description: Implicit parameter
      - name: mime_sub_type
        in: query
        type: string
        required: true
        description: Implicit parameter
      - name: auth_guid
        in: query
        type: string
        required: true
        description: Implicit parameter
      - name: file_object
        in: body
        required: true
        schema:
            type: string
            format: binary
  /prohibitionStatus/{noticeNo}:
    get:
      tags:
      - ProhibitionStatus
      security:
      - basicAuth: []
      description: Get prohibition status information
      responses:
        '200':
          description: output of the endpoint
          schema:
            $ref: '#/definitions/vipsProhibitionStatusOrdsResponse'
        '400':
          description: output of the endpoint
          schema:
            $ref: '#/definitions/errorMessage'   
      parameters:
      - name: noticeNo
        in: path
        required: true
        type: string
        description: Implicit parameter
  /disclosure/{documentId}/{authGuid}:
    get:
      tags:
      - Disclosure
      security:
      - basicAuth: []
      description: Get disclosure document information
      produces:
        - application/pdf
      responses:
        '200':
          description: A PDF file.
          schema:
            type: file
        '400':
          description: output of the endpoint
          schema:
            $ref: '#/definitions/errorMessage'   
      parameters:
      - name: documentId
        in: path
        required: true
        type: string
        description: Implicit parameter
      - name: authGuid
        in: path
        required: true
        type: string
        description: Implicit parameter
    patch:
      tags:
      - Disclosure
      security:
      - basicAuth: []
      description: Patch disclosure sent
      responses:
        '200':
          description: output of the endpoint
          schema:
            "$ref": '#/definitions/vipsDisclosureSentOrdsResponse'
        '400':
          description: output of the endpoint
          schema:
            $ref: '#/definitions/errorMessage'
      consumes:
      - application/json
      parameters:
      - name: authGuid
        in: path
        required: true
        type: string
        description: implicit
        pattern: "^[^/]+$"
      - name: documentId
        in: path
        required: true
        type: string
        description: implicit
        pattern: "^[^/]+$"
      - name: payload
        in: body
        required: true
        schema:
          "$ref": "#/definitions/vipsDisclosureSentOrdsRequest"
  /storeDocument:
    post:
      description: Digital Forms Store Document Operation
      tags: 
      - Document
      security:
      - basicAuth: []
      responses:
        '201':
          description: Successful document storage
          schema:
            "$ref": "#/definitions/vipsDocumentOrdsResponse"
        '400':
          description: Bad Request
          schema:
            $ref: "#/definitions/errorMessage"
      consumes:
      - application/pdf          
      parameters:
      - name: type_code
        in: query
        type: string
        required: true
        description: Implicit parameter
      - name: mime_type
        in: query
        type: string
        required: true
        description: Implicit parameter
      - name: mime_sub_type
        in: query
        type: string
        required: true
        description: Implicit parameter
      - name: auth_guid
        in: query
        type: string
        required: true
        description: Implicit parameter
      - name: notice_type_code
        in: query
        type: string
        required: false
        description: Implicit parameter
      - name: notice_subject_code
        in: query
        type: string
        required: false
        description: Implicit parameter  
      - name: page_count
        in: query
        type: integer
        format: int32
        required: false
        description: Implicit parameter
      - name: file_object
        in: body
        required: true
        schema:
           type: string
           format: byte         
definitions:
  healthOrdsResponse:
    type: object
    required:
    - appid
    - method
    - status
    - host
    - instance
    properties:
      appid:
        type: string
      method:
        type: string
      status:
        type: string
      host:
        type: string
      instance:
        type: string
  vipsDocumentOrdsResponse:
    type: object
    required:
    - document_id
    - status_code
    - status_message
    properties:
      document_id:
        type: string
      status_code:
        type: string
      status_message:
        type: string
  vipsProhibitionStatusOrdsResponse:
    type: object
    required: 
    - status_code
    - status_message
    - notice_type_cd
    - notice_served_dt
    - review_form_submitted_yn
    - review_created_yn
    - original_cause
    - surname_nm
    - driver_licence_seized_yn
    properties:
      status_code:
        type: string
      status_message:
        type: string
      notice_type_cd:
        type: string
      notice_served_dt:
        type: string
      review_form_submitted_yn:
        type: string
      review_created_yn:
        type: string
      original_cause:
        type: string
      surname_nm:
        type: string
      driver_licence_seized_yn:
        type: string
      disclosure:
        type: array
        items:
          type: object
          properties:
            document_id:
              type: string
            disclosed_dtm:
              type: string
      reviews:
        type: array
        items:
          type: object
          properties:
            applicationId:
              type: string
            reviewStatus:
              type: string
            reviewStartDtm:
              type: string
            reviewEndDtm:
              type: string
            receipt_number_txt:
              type: string
            reviewId:
              type: string
  vipsDisclosureSentOrdsRequest:
    type: object
    required:
    - user_id
    - disclosure_dtm
    properties:
      disclosure_dtm:
        type: string
      user_id:
        type: string
  vipsDisclosureSentOrdsResponse:
    type: object
    required:
    - status_code
    - status_message
    - upd_dtm
    properties:
      status_code:
        type: string
      status_message:
        type: string
      upd_dtm:
        type: string        
  errorMessage:
    type: object
    required:
    - status_code
    - status_message
    properties:
      status_code:
        type: string
      status_message:
        type: string      