swagger: '2.0'
info:
  title: ORDS generated API for web
  version: 1.0.0
host: dev.jag.gov.bc.ca
basePath: /ords/deva/vipsords/web
schemes:
- http
produces:
- application/json
securityDefinitions:
  basicAuth:
    type: basic
    description: HTTP Basic Authentication.
tags:
- name: Document
- name: Health
paths:
  /health:
    get:
      tags:
      - Health
      security:
      - basicAuth: []
      operationId: health
      description: Dummy endpoint to check that API calls are working
      responses:
        '200':
          description: output of the endpoint
          schema:
            $ref: '#/definitions/healthOrdsResponse'
  /vipsDocument:
    post:
      tags:
      - Document
      security:
      - basicAuth: []
      description: Store a VIPS document
      responses:
        '200':
          description: output of the endpoint
          schema:
            $ref: '#/definitions/vipsDocumentOrdsResponse'
        '400':
          description: output of the endpoint
          schema:
            $ref: '#/definitions/errorMessage'
      parameters:
      - name: type_code
        in: query
        type: string
        required: true
        description: Implicit parameter
      - name: metadata
        in: query
        type: string
        required: true
        description: Implicit parameter
      - name: mime_type
        in: query
        type: string
        required: true
        description: Implicit parameter
      - name: mime_sub_type
        in: query
        type: string
        required: true
        description: Implicit parameter
      - name: auth_guid
        in: query
        type: string
        required: true
        description: Implicit parameter
      - name: file_object
        in: body
        required: true
        schema:
          type: string
          format: binary
  /prohibitionInfo/{noticeNo}:
    get:
      tags:
      - ProhibitionStatus
      security:
      - basicAuth: []
      description: Get prohibition status information
      responses:
        '200':
          description: output of the endpoint
          schema:
            $ref: '#/definitions/vipsProhibitionStatusOrdsResponse'
        '400':
          description: output of the endpoint
          schema:
            $ref: '#/definitions/errorMessage'   
      parameters:
      - name: noticeNo
        in: path
        required: true
        type: string
        description: Implicit parameter
  /paymentStatus/{noticeNo}:
    get:
      tags:
      - PaymentStatus
      security:
      - basicAuth: []
      description: Get payment status information
      responses:
        '200':
          description: output of the endpoint
          schema:
            $ref: '#/definitions/vipsPaymentStatusOrdsResponse'
        '400':
          description: output of the endpoint
          schema:
            $ref: '#/definitions/errorMessage'   
      parameters:
      - name: noticeNo
        in: path
        required: true
        type: string
        description: Implicit parameter
  /payment/{noticeNo}:
    post:
      tags:
      - Payment
      security:
      - basicAuth: []
      description: Update payment details
      responses:
        '200':
          description: output of the endpoint
          schema:
            $ref: '#/definitions/vipsPaymentOrdsResponse'
        '400':
          description: output of the endpoint
          schema:
            $ref: '#/definitions/errorMessage'
      parameters:
      - name: noticeNo
        in: path
        required: true
        type: string
        description: Implicit parameter
      - name: payload
        in: body
        required: true
        schema:
          "$ref": "#/definitions/vipsPaymentPostRequest"
definitions:
  healthOrdsResponse:
    type: object
    required:
    - appid
    - method
    - status
    - host
    - instance
    properties:
      appid:
        type: string
      method:
        type: string
      status:
        type: string
      host:
        type: string
      instance:
        type: string
  vipsDocumentOrdsResponse:
    type: object
    required:
    - document_id
    - status_code
    - status_message
    properties:
      document_id:
        type: string
      status_code:
        type: string
      status_message:
        type: string
  vipsProhibitionStatusOrdsResponse:
    type: object
    required: 
    - effective_date
    - driver_licence_seized_yn
    - driver_last_name
    - review_status
    - cancelled_yn
    - result_code
    - result_message
    properties:
      effective_date:
        type: string
      driver_licence_seized_yn:
        type: string
      driver_last_name:
        type: string
      review_status: 
        type: string
      cancelled_yn: 
        type: string
      result_code:
        type: string
      result_message: 
        type: string            
  vipsPaymentStatusOrdsResponse:
    type: object
    required: 
    - amount_owing
    - result_code
    - result_message
    properties:
      amount_owing:
        type: string
      result_code:
        type: string
      result_message: 
        type: string 
  vipsPaymentPostRequest:
    type: object
    required:
    - card_type
    - total_price
    properties:
      card_type:
        type: string
      total_price:
        type: string
  vipsPaymentOrdsResponse:
    type: object
    required:
    - status_code
    - status_message
    properties:
      status_code:
        type: string
      status_message:
        type: string           
  errorMessage:
    type: object
    required:
    - status_code
    - status_message
    properties:
      status_code:
        type: string
      status_message:
        type: string
