swagger: '2.0'
info:
  title: ORDS generated API for web
  version: 1.0.0
host: dev.jag.gov.bc.ca
basePath: /ords/deva/vipsords/web
schemes:
- http
produces:
- application/json
securityDefinitions:
  basicAuth:
    type: basic
    description: HTTP Basic Authentication.
tags:
- name: Document
- name: Health
paths:
  /health:
    get:
      tags:
      - Health
      security:
      - basicAuth: []
      operationId: health
      description: Dummy endpoint to check that API calls are working
      responses:
        '200':
          description: output of the endpoint
          schema:
            $ref: '#/definitions/healthOrdsResponse'
  /vipsDocument:
    post:
      tags:
      - Document
      security:
      - basicAuth: []
      description: Store a VIPS document
      responses:
        '200':
          description: output of the endpoint
          schema:
            $ref: '#/definitions/vipsDocumentOrdsResponse'
        '400':
          description: output of the endpoint
          schema:
            $ref: '#/definitions/errorMessage'
      parameters:
      - name: type_code
        in: query
        type: string
        required: true
        description: Implicit parameter
      - name: metadata
        in: query
        type: string
        required: true
        description: Implicit parameter
      - name: mime_type
        in: query
        type: string
        required: true
        description: Implicit parameter
      - name: mime_sub_type
        in: query
        type: string
        required: true
        description: Implicit parameter
      - name: auth_guid
        in: query
        type: string
        required: true
        description: Implicit parameter
      - name: file_object
        in: body
        required: true
        schema:
          type: string
          format: binary
  /prohibitionStatus/{noticeNo}:
    get:
      tags:
      - ProhibitionStatus
      security:
      - basicAuth: []
      description: Get prohibition status information
      responses:
        '200':
          description: output of the endpoint
          schema:
            $ref: '#/definitions/vipsProhibitionStatusOrdsResponse'
        '400':
          description: output of the endpoint
          schema:
            $ref: '#/definitions/errorMessage'   
      parameters:
      - name: noticeNo
        in: path
        required: true
        type: string
        description: Implicit parameter
  /disclosure/{documentId}/{authGuid}:
    get:
      tags:
      - Disclosure
      security:
      - basicAuth: []
      description: Get disclosure document information
      responses:
        '200':
          description: output of the endpoint
          schema:
            $ref: '#/definitions/vipsDisclosureDocumentOrdsResponse'
        '400':
          description: output of the endpoint
          schema:
            $ref: '#/definitions/errorMessage'   
      parameters:
      - name: documentId
        in: path
        required: true
        type: string
        description: Implicit parameter
      - name: authGuid
        in: path
        required: true
        type: string
        description: Implicit parameter
  /disclosure/{noticeNo}/{documentId}/{disclosedDtm}/{authGuid}:
    patch:
      tags:
      - Disclosure
      security:
      - basicAuth: []
      description: Patch disclosure sent
      responses:
        '200':
          description: output of the endpoint
          schema:
            "$ref": '#/definitions/vipsDisclosureSentOrdsResponse'
        '400':
          description: output of the endpoint
          schema:
            $ref: '#/definitions/errorMessage'
      parameters:
      - name: noticeNo
        in: path
        required: true
        type: string
        description: Implicit parameter
      - name: documentId
        in: path
        required: true
        type: string
        description: Implicit parameter
      - name: disclosedDtm
        in: path
        required: true
        type: string
        description: Implicit parameter
      - name: authGuid
        in: path
        required: true
        type: string
        description: Implicit parameter
definitions:
  healthOrdsResponse:
    type: object
    required:
    - appid
    - method
    - status
    - host
    - instance
    properties:
      appid:
        type: string
      method:
        type: string
      status:
        type: string
      host:
        type: string
      instance:
        type: string
  vipsDocumentOrdsResponse:
    type: object
    required:
    - document_id
    - status_code
    - status_message
    properties:
      document_id:
        type: string
      status_code:
        type: string
      status_message:
        type: string
  vipsProhibitionStatusOrdsResponse:
    type: object
    required: 
    - status_code
    - status_message
    - notice_type_cd
    - effective_dt
    - review_form_submitted_yn
    - review_created_yn
    - original_cause
    - surname_nm
    - driver_licence_seized_yn
    - review_start_tm
    - review_end_tm
    - receipt_number_txt
    properties:
      status_code:
        type: string
      status_message:
        type: string
      notice_type_cd:
        type: string
      effective_dt:
        type: string
      review_form_submitted_yn:
        type: string
      review_created_yn:
        type: string
      original_cause:
        type: string
      surname_nm:
        type: string
      driver_licence_seized_yn:
        type: string  
      review_start_tm:
        type: string
      review_end_tm:
        type: string
      receipt_number_txt:
        type: string   
      disclosure:
        type: array
        items:
          type: object
          properties:
            document_id:
              type: string
            disclosed_dtm:
              type: string   
  vipsDisclosureDocumentOrdsResponse:
    type: object
    required: 
    - status_code
    - status_message
    - mime_type
    - document
    properties:
      status_code:
        type: string
      status_message:
        type: string
      mime_type:
        type: string
      document:
        type: string  
  vipsDisclosureSentOrdsResponse:
    type: object
    required:
    - status_code
    - status_message
    - upd_dtm
    properties:
      status_code:
        type: string
      status_message:
        type: string
      upd_dtm:
        type: string        
  errorMessage:
    type: object
    required:
    - status_code
    - status_message
    properties:
      status_code:
        type: string
      status_message:
        type: string
