swagger: '2.0'
info:
  title: ORDS generated API for web
  version: 1.0.0
host: dev.jag.gov.bc.ca
basePath: /ords/deva/vipsords/web
schemes:
- http
produces:
- application/json
securityDefinitions:
  basicAuth:
    type: basic
    description: HTTP Basic Authentication.
tags:
- name: Document
- name: Health
paths:
  /health:
    get:
      tags:
      - Health
      security:
      - basicAuth: []
      operationId: health
      description: Dummy endpoint to check that API calls are working
      responses:
        '200':
          description: output of the endpoint
          schema:
            $ref: '#/definitions/healthOrdsResponse'
  /vipsDocument:
    post:
      tags:
      - Document
      security:
      - basicAuth: []
      description: Store a VIPS document
      responses:
        '200':
          description: output of the endpoint
          schema:
            $ref: '#/definitions/vipsDocumentOrdsResponse'
        '400':
          description: output of the endpoint
          schema:
            $ref: '#/definitions/errorMessage'
      parameters:
      - name: type_code
        in: query
        type: string
        required: true
        description: Implicit parameter
      - name: metadata
        in: query
        type: string
        required: true
        description: Implicit parameter
      - name: mime_type
        in: query
        type: string
        required: true
        description: Implicit parameter
      - name: mime_sub_type
        in: query
        type: string
        required: true
        description: Implicit parameter
      - name: auth_guid
        in: query
        type: string
        required: true
        description: Implicit parameter
      - name: file_object
        in: body
        required: true
        schema:
          type: string
          format: binary
definitions:
  healthOrdsResponse:
    type: object
    required:
    - appid
    - method
    - status
    - host
    - instance
    properties:
      appid:
        type: string
      method:
        type: string
      status:
        type: string
      host:
        type: string
      instance:
        type: string
  vipsDocumentOrdsResponse:
    type: object
    required:
    - document_id
    - status_code
    - status_message
    properties:
      document_id:
        type: string
      status_code:
        type: string
      status_message:
        type: string
  errorMessage:
    type: object
    required:
    - status_code
    - status_message
    properties:
      status_code:
        type: string
      status_message:
        type: string
